run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - exhaustruct
    - gofmt
    - goimports
    - golint
    - ifshort
    - interfacer
    - maligned
    - nonamedreturns
    - nosnakecase
    - scopelint
    - structcheck
    - testpackage
    - varcheck
    - varnamelen