name: Check

on:
  push:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04
    name: check (${{ matrix.go}})
    strategy:
      matrix:
        go: [ 1.24, 1.25, 1.26 ] # TODO(jhorsts): pin digests
    continue-on-error: true
    steps:
      - uses: EarthBuild/actions-setup@7987dab5a16b4ae7225b079d474f20857771d89c # main
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: echo "go_version=${{ matrix.go }}-alpine3.23" >> .arg
      - name: Lint
        run: earth  --ci +lint
      - name: Test
        run: earth --ci +test
      - name: Go Vulnerability Check
        run: earth --ci +govulncheck
