name: Check

on:
  push:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04
    name: check (${{ matrix.go}})
    strategy:
      matrix:
        go: [1.24, 1.25, 1.26] # TODO(jhorsts): pin digests
    continue-on-error: true
    steps:
      - uses: earthbuild/actions-setup@f4d20223e70dbb43b5fc08c4d857ab9cf0dbf3ae # v2.2.0
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: echo "go_version=${{ matrix.go }}-alpine3.23" >> .arg
      - name: Lint
        run: earth  --ci +lint
      - name: Test
        run: earth --ci +test
      - name: Go Vulnerability Check
        run: earth --ci +govulncheck
